// <auto-generated />
using System;
using HappyHour.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HappyHour.Migrations.TorrentDb
{
    [DbContext(typeof(TorrentDbContext))]
    partial class TorrentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("HappyHour.Model.Magnet", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MagnetUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TorrentKey")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.HasIndex("TorrentKey");

                    b.ToTable("Magnets");
                });

            modelBuilder.Entity("HappyHour.Model.StringData", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TorrentKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("TorrentKey");

                    b.ToTable("Strings");
                });

            modelBuilder.Entity("HappyHour.Model.Torrent", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("PID")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<char>("StatusCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Torrents");
                });

            modelBuilder.Entity("HappyHour.Model.Magnet", b =>
                {
                    b.HasOne("HappyHour.Model.Torrent", null)
                        .WithMany("MagnetUrls")
                        .HasForeignKey("TorrentKey");
                });

            modelBuilder.Entity("HappyHour.Model.StringData", b =>
                {
                    b.HasOne("HappyHour.Model.Torrent", null)
                        .WithMany("Screenshots")
                        .HasForeignKey("TorrentKey");
                });

            modelBuilder.Entity("HappyHour.Model.Torrent", b =>
                {
                    b.Navigation("MagnetUrls");

                    b.Navigation("Screenshots");
                });
#pragma warning restore 612, 618
        }
    }
}
