// <auto-generated />
using System;
using HappyHour.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HappyHour.Migrations.MovieDb
{
    [DbContext(typeof(MovieDbContext))]
    partial class MovieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.Property<int>("ActorsKey")
                        .HasColumnType("int");

                    b.Property<int>("MoviesKey")
                        .HasColumnType("int");

                    b.HasKey("ActorsKey", "MoviesKey");

                    b.HasIndex("MoviesKey");

                    b.ToTable("ActorMovie");
                });

            modelBuilder.Entity("GenreMovie", b =>
                {
                    b.Property<int>("GenresKey")
                        .HasColumnType("int");

                    b.Property<int>("MoviesKey")
                        .HasColumnType("int");

                    b.HasKey("GenresKey", "MoviesKey");

                    b.HasIndex("MoviesKey");

                    b.ToTable("GenreMovie");
                });

            modelBuilder.Entity("HappyHour.Model.Actor", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Key"));

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ThumbKey")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.HasIndex("ThumbKey");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("HappyHour.Model.ActorName", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Key"));

                    b.Property<int?>("ActorKey")
                        .HasColumnType("int");

                    b.Property<int>("Alias")
                        .HasColumnType("int");

                    b.Property<int?>("NameKey")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.HasIndex("ActorKey");

                    b.HasIndex("NameKey");

                    b.ToTable("ActorNames");
                });

            modelBuilder.Entity("HappyHour.Model.Genre", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Key"));

                    b.HasKey("Key");

                    b.ToTable("MovieGenres");
                });

            modelBuilder.Entity("HappyHour.Model.ImageBlob", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Key"));

                    b.Property<int?>("ActorKey")
                        .HasColumnType("int");

                    b.Property<byte[]>("Data")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("Hash")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int?>("MovieKey")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.HasIndex("ActorKey");

                    b.HasIndex("MovieKey");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("HappyHour.Model.Label", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Key"));

                    b.Property<int?>("LogoKey")
                        .HasColumnType("int");

                    b.Property<int?>("MakerKey")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.HasIndex("LogoKey");

                    b.HasIndex("MakerKey");

                    b.ToTable("Lables");
                });

            modelBuilder.Entity("HappyHour.Model.LongText", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Key"));

                    b.Property<string>("Lang")
                        .HasColumnType("longtext");

                    b.Property<int?>("MovieKey")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasMaxLength(4906)
                        .HasColumnType("varchar(4906)");

                    b.HasKey("Key");

                    b.HasIndex("MovieKey");

                    b.ToTable("LongTexts");
                });

            modelBuilder.Entity("HappyHour.Model.Maker", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Key"));

                    b.Property<int?>("LogoKey")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.HasIndex("LogoKey");

                    b.ToTable("Makers");
                });

            modelBuilder.Entity("HappyHour.Model.Movie", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Key"));

                    b.Property<string>("AltPID")
                        .HasColumnType("longtext");

                    b.Property<bool>("Censored")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("CoverKey")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateDeleted")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateReleased")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LabelKey")
                        .HasColumnType("int");

                    b.Property<string>("PID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("SeriesKey")
                        .HasColumnType("int");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("longtext");

                    b.HasKey("Key");

                    b.HasIndex("CoverKey");

                    b.HasIndex("LabelKey");

                    b.HasIndex("SeriesKey");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("HappyHour.Model.Rating", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Key"));

                    b.Property<int?>("MovieKey")
                        .HasColumnType("int");

                    b.Property<float>("Rate")
                        .HasColumnType("float");

                    b.Property<string>("SiteUrl")
                        .HasColumnType("longtext");

                    b.HasKey("Key");

                    b.HasIndex("MovieKey");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("HappyHour.Model.Series", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Key"));

                    b.HasKey("Key");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("HappyHour.Model.ShortText", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Key"));

                    b.Property<int?>("GenreKey")
                        .HasColumnType("int");

                    b.Property<int?>("LabelKey")
                        .HasColumnType("int");

                    b.Property<string>("Lang")
                        .HasColumnType("longtext");

                    b.Property<int?>("MakerKey")
                        .HasColumnType("int");

                    b.Property<int?>("MovieKey")
                        .HasColumnType("int");

                    b.Property<int?>("SeriesKey")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.HasKey("Key");

                    b.HasIndex("GenreKey");

                    b.HasIndex("LabelKey");

                    b.HasIndex("MakerKey");

                    b.HasIndex("MovieKey");

                    b.HasIndex("SeriesKey");

                    b.ToTable("ShortTexts");
                });

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.HasOne("HappyHour.Model.Actor", null)
                        .WithMany()
                        .HasForeignKey("ActorsKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HappyHour.Model.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenreMovie", b =>
                {
                    b.HasOne("HappyHour.Model.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HappyHour.Model.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HappyHour.Model.Actor", b =>
                {
                    b.HasOne("HappyHour.Model.ImageBlob", "Thumb")
                        .WithMany()
                        .HasForeignKey("ThumbKey");

                    b.Navigation("Thumb");
                });

            modelBuilder.Entity("HappyHour.Model.ActorName", b =>
                {
                    b.HasOne("HappyHour.Model.Actor", "Actor")
                        .WithMany("Names")
                        .HasForeignKey("ActorKey");

                    b.HasOne("HappyHour.Model.ShortText", "Name")
                        .WithMany()
                        .HasForeignKey("NameKey");

                    b.Navigation("Actor");

                    b.Navigation("Name");
                });

            modelBuilder.Entity("HappyHour.Model.ImageBlob", b =>
                {
                    b.HasOne("HappyHour.Model.Actor", null)
                        .WithMany("Pictures")
                        .HasForeignKey("ActorKey");

                    b.HasOne("HappyHour.Model.Movie", null)
                        .WithMany("Screenshots")
                        .HasForeignKey("MovieKey");
                });

            modelBuilder.Entity("HappyHour.Model.Label", b =>
                {
                    b.HasOne("HappyHour.Model.ImageBlob", "Logo")
                        .WithMany()
                        .HasForeignKey("LogoKey");

                    b.HasOne("HappyHour.Model.Maker", "Maker")
                        .WithMany("Labels")
                        .HasForeignKey("MakerKey");

                    b.Navigation("Logo");

                    b.Navigation("Maker");
                });

            modelBuilder.Entity("HappyHour.Model.LongText", b =>
                {
                    b.HasOne("HappyHour.Model.Movie", null)
                        .WithMany("Plot")
                        .HasForeignKey("MovieKey");
                });

            modelBuilder.Entity("HappyHour.Model.Maker", b =>
                {
                    b.HasOne("HappyHour.Model.ImageBlob", "Logo")
                        .WithMany()
                        .HasForeignKey("LogoKey");

                    b.Navigation("Logo");
                });

            modelBuilder.Entity("HappyHour.Model.Movie", b =>
                {
                    b.HasOne("HappyHour.Model.ImageBlob", "Cover")
                        .WithMany()
                        .HasForeignKey("CoverKey");

                    b.HasOne("HappyHour.Model.Label", "Label")
                        .WithMany("Movies")
                        .HasForeignKey("LabelKey");

                    b.HasOne("HappyHour.Model.Series", "Series")
                        .WithMany("Movies")
                        .HasForeignKey("SeriesKey");

                    b.Navigation("Cover");

                    b.Navigation("Label");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("HappyHour.Model.Rating", b =>
                {
                    b.HasOne("HappyHour.Model.Movie", "Movie")
                        .WithMany("Ratings")
                        .HasForeignKey("MovieKey");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("HappyHour.Model.ShortText", b =>
                {
                    b.HasOne("HappyHour.Model.Genre", null)
                        .WithMany("Name")
                        .HasForeignKey("GenreKey");

                    b.HasOne("HappyHour.Model.Label", null)
                        .WithMany("Name")
                        .HasForeignKey("LabelKey");

                    b.HasOne("HappyHour.Model.Maker", null)
                        .WithMany("Name")
                        .HasForeignKey("MakerKey");

                    b.HasOne("HappyHour.Model.Movie", null)
                        .WithMany("Title")
                        .HasForeignKey("MovieKey");

                    b.HasOne("HappyHour.Model.Series", null)
                        .WithMany("Name")
                        .HasForeignKey("SeriesKey");
                });

            modelBuilder.Entity("HappyHour.Model.Actor", b =>
                {
                    b.Navigation("Names");

                    b.Navigation("Pictures");
                });

            modelBuilder.Entity("HappyHour.Model.Genre", b =>
                {
                    b.Navigation("Name");
                });

            modelBuilder.Entity("HappyHour.Model.Label", b =>
                {
                    b.Navigation("Movies");

                    b.Navigation("Name");
                });

            modelBuilder.Entity("HappyHour.Model.Maker", b =>
                {
                    b.Navigation("Labels");

                    b.Navigation("Name");
                });

            modelBuilder.Entity("HappyHour.Model.Movie", b =>
                {
                    b.Navigation("Plot");

                    b.Navigation("Ratings");

                    b.Navigation("Screenshots");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("HappyHour.Model.Series", b =>
                {
                    b.Navigation("Movies");

                    b.Navigation("Name");
                });
#pragma warning restore 612, 618
        }
    }
}
